### ISSUE TITLE
Unable to change the material color of glb model in scene (submeshIndex (0) is out of range. It must be less than the submeshCount (0).)

### ISSUE THREAD

**Issue by iAmJuan550** [ThomasGorisse/sceneform-android-sdk#163]
I converted my .obj fle to .glb file by running the following command on Ubuntu 20.04:

`obj2gltf -i anchor.obj -o anchor.glb`

I put the anchor.glb file in the raw folder inside the res directory. Then, I use the following code to load the renderable:

```
ModelRenderable.builder()
                .setSource(context, R.raw.anchor)
                .setIsFilamentGltf(true)
                .setAsyncLoadEnabled(true)
                .build()
                .thenAccept(renderable -> {
                    anchorRenderable = renderable;
                    anchorRenderable.setShadowCaster(false);
                    anchorRenderable.setShadowReceiver(false);
                    Material changedMaterial = anchorRenderable.getMaterial().makeCopy();
                    changedMaterial.setFloat3("baseColorTint",
                            new Color(android.graphics.Color.rgb(0, 0, 255)));
                    anchorRenderable.setMaterial(changedMaterial);
                });
```

When I assign the `anchorRenderable` to my AnchorNode and try to change the color of the renderable:

```
Renderable renderable = anchorNode.getRenderable().makeCopy();
Material changedMaterial = renderable.getMaterial();
```
I get the following error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.memex.eu, PID: 28160
    java.lang.IllegalArgumentException: submeshIndex (0) is out of range. It must be less than the submeshCount (0).
        at com.google.ar.sceneform.rendering.Renderable.makeSubmeshOutOfRangeException(Renderable.java:326)
        at com.google.ar.sceneform.rendering.Renderable.getMaterial(Renderable.java:144)
        at com.google.ar.sceneform.rendering.Renderable.getMaterial(Renderable.java:133)
```

Is there some extra information needed by sceneform to let me change the color of the glb model in the scene?

**Comment by ThomasGorisse** [comment]
You should apply the material to the `RenderableInstance` not the  `Renderable`
```java
renderableInstance = anchorNode.getRenderableInstance()
renderableInstance.setMaterial(...)
```

**Comment by iAmJuan550** [comment]
@ThomasGorisse I tried this but then when I do `anchorNode.setRenderable(renderableInstance.getRenderable())` nothing happens and the anchor's color remains the same

**Comment by ThomasGorisse** [comment]
Remove this last line
```java
anchorNode.setRenderable(renderableInstance.getRenderable());
```
and if your renderable is a gltf, make sure to call this
```java
changedMaterial.setInt("baseColorIndex", 0);
```

**Comment by memostark** [comment]
@ThomasGorisse I'm also trying to change the color of a GLB following your instructions but I'm getting a different error when setting the material.
```
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:278)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:284)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:669)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:642)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:484)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:571)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:590)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:452)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.set(ArrayList.java:453)
        at com.google.ar.sceneform.rendering.RenderableInstance.setMaterial(RenderableInstance.java:415)
        at com.google.ar.sceneform.rendering.RenderableInstance.setMaterial(RenderableInstance.java:405)
        at com.google.ar.sceneform.rendering.RenderableInstance.setMaterial(RenderableInstance.java:397)
```

Here is the code
```
Node arrow = new Node();
arrow.setLocalScale(scaleVector);
arrow.setRenderable(renderable);
anchorNode.addChild(arrow);

RenderableInstance renderableInstance = arrow.getRenderableInstance();
Material changedMaterial = renderableInstance.getMaterial();
changedMaterial.setInt("baseColorIndex", 0);
changedMaterial.setFloat3("baseColorTint", new Color(android.graphics.Color.parseColor(color)));

renderableInstance.setMaterial(changedMaterial);
```

The last line throws the exception. The 3D model is visible on the screen but without the desired color.
