### ISSUE TITLE
I cannot play animation by using below code .

### ISSUE THREAD

**Issue by suryanadiminti99** [ThomasGorisse/sceneform-android-sdk#56]
While playing animation using animation track name . Getting this error . If i remove (AnimatableModel) , it showing error. 

`ObjectAnimator walkAnimator = ModelAnimator.ofAnimation((AnimatableModel) transformableNode, animation_type);
                        walkAnimator.setStartDelay(milli);
                        walkAnimator.setDuration(durTime);
                        walkAnimator.start();`

`Caused by: java.lang.ClassCastException: com.google.ar.sceneform.Node cannot be cast to com.google.ar.sceneform.animation.AnimatableModel
2021-05-01 16:50:34.419 21486-21486/com.plugxr.cloudanchors W/System.err:     at com.plugxr.cloudanchors.CreateAchor.ArActivity.placeResolveCloudAnchorModel(ArActivity.java:3775)
2021-05-01 16:50:34.419 21486-21486/com.plugxr.cloudanchors W/System.err:     at com.plugxr.cloudanchors.CreateAchor.ArActivity.lambda$createResolveCloudAnchorModel$29$ArActivity(ArActivity.java:3516)`

**Comment by suryanadiminti99** [comment]
@ThomasGorisse Hi, I am unable to delete it . That's why i moved to closed issue.
